### ISSUE TITLE
Panic in subgroup_fft_in_place benchmark

### ISSUE THREAD

**Issue by daira** [arkworks-rs/algebra#281]
```
$ cargo +nightly bench
[...]
Benchmarking "mnt6_753 - mixed radix" - subgroup_fft_in_place/1048576: Warming up for 3.0000 sthread 'main' panicked at 'called `Option::unwrap()` on a `None` value', poly-benches/benches/fft.rs:43:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: bench failed
```
This was on the `add-biginterger-into-from-biguint` branch; not sure if that's relevant. I will try later to see if I can reproduce this with a backtrace and on master.

**Comment by daira** [comment]
This is reproducible on master:
```
daira@katava:~/research/algebra/poly-benches$ git rev-parse HEAD
ebd1c3f14a46f2a9992727d5ef51cf9ca963fb97
daira@katava:~/research/algebra/poly-benches$ RUST_BACKTRACE=1 cargo +nightly bench 'subgroup_fft_in_place/1048576'
    Finished bench [optimized] target(s) in 0.05s
     Running /home/daira/research/algebra/target/release/deps/dense_multilinear-f05f1341652c05a9
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

     Running /home/daira/research/algebra/target/release/deps/dense_uv_polynomial-44cf4355ca5d175a
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

     Running /home/daira/research/algebra/target/release/deps/fft-a2ece2d48720aaf1
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Benchmarking "bls12_381 - radix2" - subgroup_fft_in_place/1048576: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 57.0s, or reduce sample count to 10.
"bls12_381 - radix2" - subgroup_fft_in_place/1048576                                                                            
                        time:   [562.09 ms 562.70 ms 563.41 ms]
                        change: [+0.5952% +0.7425% +0.9031%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe

Benchmarking "mnt6_753 - mixed radix" - subgroup_fft_in_place/1048576: Warming up for 3.0000 sthread 'main' panicked at 'called `Option::unwrap()` on a `None` value', poly-benches/benches/fft.rs:43:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3e826bb11228508fbe749e594038d6727208aa94/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/3e826bb11228508fbe749e594038d6727208aa94/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/3e826bb11228508fbe749e594038d6727208aa94/library/core/src/panicking.rs:50:5
   3: fft::fft_common_setup
   4: fft::bench_fft_in_place
   5: <criterion::routine::Function<M,F,T> as criterion::routine::Routine<M,T>>::warm_up
   6: criterion::routine::Routine::sample
   7: criterion::analysis::common
   8: criterion::benchmark_group::BenchmarkGroup<M>::bench_with_input
   9: fft::setup_bench
  10: fft::fft_benches
  11: fft::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: bench failed
```

**Comment by Pratyush** [comment]
Hmm, let me try to reproduce this. Thanks for the heads up!

**Comment by weikengchen** [comment]
Found the reason.

The bench program considers degrees of 2^15 to 2^22. 

This is okay for BLS12-381::Fr, but not good for MNT6-753::Fr

```use ark_test_curves::mnt4_753::Fq as mnt6_753_fr;```

https://github.com/arkworks-rs/algebra/blob/e7eeea3f2ac7d621f68089b978097403dd02e91b/poly-benches/benches/fft.rs#L8

The latter only has 2^15 * 5^2, which is smaller than 1048576, aka 2^20.

We can separate the benchmark size of the two curves, by separating the `default_size_range` for each curve.

**Comment by weikengchen** [comment]
A PR is on the way.
